# /opt/telegram-reminder/telegram-reminder/docker-compose.yml
services:
  telegram-reminder:            # ← вместо bot
    image: ${DOCKERHUB_USER}/telegram-reminder:latest
    container_name: telegram-reminder  # фиксируем именно такое имя
    restart: unless-stopped
    env_file:
      - .env
