name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - name: Check gofmt
        run: |
          gofmt -w $(git ls-files '*.go')
          git diff --exit-code
      - run: go build ./...
      - run: go test ./...
