name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2

      - run: go vet ./...

      - name: Auto format with gofmt
        run: |
          gofmt -w -s $(git ls-files '*.go')

      - name: Commit formatting changes (if any)
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet; then
            git add .
            git commit -m "style: auto-format via gofmt"
            git push
          fi

      - run: go build ./...
      - run: go test ./...
